apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: main-proj
  namespace: ${namespace}
spec:
  sourceRepos:
      ${indent(6, yamlencode(repositories_url))}
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'