apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-cluster-secretstore
  namespace: ${namespace}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${region}
      auth:
        jwt:
          serviceAccountRef:
            name: ${external_secrets_serviceaccount}
            namespace: ${external_secrets_namespace}