apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-sso-secret
  namespace: ${namespace}
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${secret_store_ref_name}
    kind: ${secret_store_ref_kind}
  target:
    name: ${argocd_github_sso_secret}
  dataFrom:
  - extract:
      key: ${awssm_secret_name}