fullnameOverride: ${release_name}
env:
  AWS_REGION: ${region}
  AWS_DEFAULT_REGION: ${region}
serviceAccount:
  create: true
  name: ${sa_name}
  annotations:
    eks.amazonaws.com/role-arn: ${irsa_role}
podSecurityContext:
  fsGroup: 65534
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
installCRDs: true
%{ if has_dedicated_infra_nodes }
## This configuration for 0.8.7 Chart version, later versions has global configuration!
## Like the following:
# global:
#   tolerations:
#     - key: CriticalAddonsOnly
#       operator: Exists
#   nodeSelector:
#     role: infra
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
nodeSelector:
  role: infra
webhook:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  nodeSelector:
    role: infra
certController:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  nodeSelector:
    role: infra
%{ endif }
