fullnameOverride: ${release_name}
serviceAccount:
  create: true
  name: ${sa_name}
  annotations:
    eks.amazonaws.com/role-arn: ${irsa_role}
domainFilters:
  - ${domain}
txtOwnerId: external-dns-${cluster_name}
policy: sync
provider: aws
aws:
  region: ${region}
%{ if has_dedicated_infra_nodes }
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
nodeSelector:
  role: infra
%{ endif }
