fullnameOverride: ${release_name}
clusterName: ${cluster_name}
region: ${region}
vpcId: ${vpc_id}
enableServiceMutatorWebhook: false
serviceAccount:
  create: true
  name: ${sa_name}
  annotations:
    eks.amazonaws.com/role-arn: ${irsa_role}
%{ if has_dedicated_infra_nodes }
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
nodeSelector:
  role: infra
%{ endif }
