apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-github-sso-secret
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "global-cluster-secretstore"
    kind: ClusterSecretStore
  target:
    name: ${grafana_github_sso_secret}
  dataFrom:
    - extract:
        key: ${awssm_secret_name}
